// Generated by CoffeeScript 1.6.3
(function() {
  (function($) {
    return $.fn.collapseMe = function(options) {
      var article, content, defaults, whats_clicked;
      this.addClass("collapse-Me");
      defaults = {
        speed: 500,
        closeText: "-",
        openText: "+",
        color: "#000000",
        addCSS: true,
        applyTo: "article",
        contentClass: ".content",
        clickItem: false,
        beforeOpen: function() {},
        afterOpen: function() {},
        beforeClose: function() {},
        afterClose: function() {},
        stepOpen: function() {},
        stepClose: function() {}
      };
      options = $.extend(defaults, options);
      content = this.find(options["applyTo"]).find(options["contentClass"]);
      article = this.find(options["applyTo"]);
      article.addClass("collapse-item");
      article.each(function() {
        if ($(this).hasClass("expanded")) {
          return $(this).append("<span class='collapse-icon collapse-trigger'>" + options['closeText'] + "</span>");
        } else {
          return $(this).append("<span class='collapse-icon collapse-trigger'>" + options['openText'] + "</span>");
        }
      });
      content.each(function() {
        if (!$(this).parent().hasClass("expanded")) {
          return $(this).css("display", "none");
        }
      });
      content.addClass("collapse-content");
      if (options['addCSS']) {
        article.css("position", "relative");
        $("span.collapse-icon").css({
          "position": "absolute",
          "top": "13px",
          "right": "10px",
          "font-size": "15px",
          "color": options['color']
        });
      }
      if (options['clickItem']) {
        whats_clicked = article;
      } else {
        whats_clicked = this.find(".collapse-item").find(".collapse-trigger");
      }
      return whats_clicked.click(function() {
        var $this;
        if (options['clickItem']) {
          $this = $(this);
        } else {
          $this = $(this).parents(".collapse-item");
        }
        $this.find("collapse-icon").html(options['openText']);
        if ($this.hasClass("expanded")) {
          $(".collapse-icon").html(options['openText']);
          $this.find(".collapse-icon").html(options['openText']);
          options['beforeClose'].call(this);
          content.slideUp({
            duration: options['speed'],
            step: options['stepClose']
          });
          return $this.removeClass("expanded");
        } else {
          article.removeClass("expanded");
          $(".collapse-icon").html(options['openText']);
          content.slideUp(options['speed'], function() {
            return $(this).parent(options['applyTo']).removeClass("expanded");
          });
          options['beforeOpen'].call(this);
          $this.find(options['contentClass']).slideDown({
            duration: options['speed'],
            complete: options['afterOpen'],
            step: options['stepOpen']
          });
          $this.addClass("expanded");
          return $this.find('.collapse-icon').html(options['closeText']);
        }
      });
    };
  })(jQuery);

}).call(this);
